config/routes.rb
Rails.application.routes.draw do
  resources :banks
  resources :registrations do
    collection do
      get :user_registration
    end
  end

  resources :banks
  resources :ci_companies
  resources :banking_users do
    put :disable
    put :enable
  end
  
  resources :company_inspectors
  resources :user_invitations do
    collection do
      get :banking_user_invitation
      post :send_banking_user_invitation
    end
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable, polymorphic: true
  belongs_to :state, class_name: 'State', foreign_key: :state_id
  belongs_to :country, class_name: 'Country', foreign_key: :country_id
end

app/models/bank.rb
class Bank < ActiveRecord::Base
  has_many :projects
  has_many :cics, through: :projects
  has_many :employees, as: :employable
  has_many :users, through: :employees
  has_one :address, as: :addressable
  accepts_nested_attributes_for :address
  validates :bank_name , presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/ci_company.rb
class CiCompany < ActiveRecord::Base
  has_many :employees, as: :employable
  has_many :users, through: :employees
  has_many :projects
  has_many :banks, through: :projects
  has_many :project_inspection_requests, through: :projects
  has_one :address, as: :addressable
  accepts_nested_attributes_for :address
  validates :ci_company_name , presence: true
  validates_format_of :ci_company_email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :addresses
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :addresses,  as: :addressable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  # authorize_resource :bank
  before_filter :find_by_bank_id, only: [:edit, :update, :show]
  before_filter :is_bank_admin_or_is_banking_professional, only: [:index]
  def index
    @banks = Bank.page(params[:page]).per(t('pagination.per_page'))
  end

  def new
    @bank = Bank.new.tap do |bank|
      bank.address = Address.new
    end
  end

  def create
    @bank = Bank.create(bank_params)
    if @bank.save
      #if #current_user.is_bank_admin? || current_user.is_cic_admin? && !current_user.user_invitations.present?
        #employee = Employee.new({user_id: current_user.id, employable: @bank})
        #employee.save
      #end
      flash[:notice] = "Bank Registered Successfully"
      # if current_user.is_bank_admin? 
      #   redirect_to bank_path(@bank)
      # else
        redirect_to banks_path
      # end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @bank.update_attributes(bank_params)
      flash[:notice] = "Bank data Successfully updated"
      if current_user.is_bank_admin?
        redirect_to bank_path(@bank)
      else
        redirect_to banks_path
      end
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    bank = Bank.find(params[:id])
    bank.delete
    flash[:notice] = "Bank Deleted Successfully"
    redirect_to banks_path
  end

  private

  def bank_params
    params.require(:bank).permit(:id, :bank_name, :phone_number, :email, :url, :address_attributes => [:state_id, :country_id, :street, :city])
  end

  def user_employee_params
    params.require(:employee).permit(:user_id, :employable_id, :employable_type)
  end

  def find_by_bank_id
    @bank = Bank.find(params[:id])
  end

  def is_bank_admin_or_is_banking_professional
    # if current_user.is_bank_admin? && !current_user.employee.employable.present?
    #   redirect_to new_bank_path 
    # elsif current_user.is_bank_admin? && current_user.employee.present?
    #   redirect_to bank_path(current_user.employee.employable.id)
    # else
    #   banks_path
    # end
    banks_path
  end
end

app/controllers/ci_companies_controller.rb
class CiCompaniesController < ApplicationController
  # authorize_resource :ci_company
  before_filter :find_by_id, only: [:edit, :update, :destroy]
  def index
    @ci_companies = CiCompany.page(params[:page]).per(t('pagination.per_page'))
  end

  def new
    @ci_company = CiCompany.new.tap do |ci_company|
      ci_company.address = Address.new
    end
  end

  def create
    @ci_company = CiCompany.create(ci_company_params)
    if @ci_company.save
      flash[:notice] = "Ci Company  Registered Successfully"
      redirect_to ci_companies_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @ci_company.update_attributes(ci_company_params)
      flash[:notice] = "Ci Company Successfully updated"
      redirect_to ci_companies_path
    else
      render :edit
    end
  end

  def destroy
    ci_company.delete
    flash[:notice] = "Ci Company Deleted Successfully"
    redirect_to ci_companies_path
  end

  private

  def find_by_id
    CiCompany.find(params[:id])
  end

  def ci_company_params
    params.require(:ci_company).permit(:id, :ci_company_name, :phone_number, :ci_company_email, :url, :address_attributes => [:state_id, :country_id, :street, :city])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banking_users_helper.rb
module BankingUsersHelper
end

app/helpers/banks_helper.rb
module BanksHelper
  def set_bank_label
    current_user.is_bank_admin? ? 'My Bank' : 'Banks'
  end

  def set_add_show_bank_link
    # employee = current_user.employee.employable if current_user.employee.present?
    # if current_user.is_bank_admin? && !employee.present?
    #   new_bank_path
    # elsif current_user.is_banking_professional? && employee.present?
    #   bank_path(@bank)      
    # else
    #   banks_path
    # end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_invitations_helper.rb
module UserInvitationsHelper
end

app/views/banks/_form.html.haml
= form_for @bank do |f|
  .col-md-6
    .box.box-primary
      .box-header
        %h3.box-title
        .box-body
          - if @bank.errors[:bank_name].present?
            .form-group.has-error
              = f.label :Name
              = f.text_field :bank_name, placeholder: "#{@bank.errors.messages[:bank_name].join(",")}", :class => 'form-control'
          - else
            .form-group
              = f.label :Name
              = f.text_field :bank_name, placeholder: 'Enter Name', :class => 'form-control'
          .form-group
            = f.label :Phone
            = f.text_field :phone_number, placeholder: 'Enter Phone', :class => 'form-control'
          - if @bank.errors[:email].present?
            .form-group.has-error
              = f.label :Email
              = f.text_field :email, placeholder: "#{@bank.errors.messages[:email].join(",")}", :class => 'form-control'
          - else
            .form-group
              = f.label :Email
              = f.text_field :email, placeholder: 'Enter email', :class => 'form-control'
          .form-group
            = f.label :URL
            = f.text_field :url, placeholder: 'Enter URL', :class => 'form-control'
  .col-md-6
    .box.box-warning
      .box-header
        %h3.box-title Address
        .box-body
          = f.fields_for :address do |addresses_form|
            .form-group
              #{addresses_form.label :Country}
            .form-group
              #{addresses_form.collection_select :country_id, Country.all, :id, :name, {include_blank: false}, {class: 'form-control'}}
            .form-group
              #{addresses_form.label :State}
            .form-group
              #{addresses_form.collection_select :state_id, State.all, :id, :name, {include_blank: 'Select State'}, {class: 'form-control'}}
            .form-group
              #{addresses_form.label :Street}
            .form-group
              #{addresses_form.text_field :street, :class => 'form-control', placeholder: 'Enter Street'}
            .form-group
              #{addresses_form.label :City}
            .form-group
              #{addresses_form.text_field :city, :class => 'form-control', placeholder: 'Enter City'}
    .box-warning{:style => 'position: relative;right: 513px;'}
      .box-footer
        %button.btn.btn-primary{:type => 'submit'} Submit

app/views/banks/_list_of_banks.html.haml
- @banks.each_with_index do |bank, index|
  %tr
    %td<
      = index + 1
    %td< 
      = bank.bank_name
    %td<
      = bank.email
    %td<
      = bank.phone_number
    %td<
      / = link_to(edit_bank_path(bank), class: 'green', title: 'Edit') do
      /   %i.fa.fa-fw.fa-pencil
      / = link_to(bank_path(bank), method: :delete, data: { confirm: 'Are you sure?' }, class: 'green', title: 'Delete') do
      /   %i.fa.fa-fw.fa-bitbucket

app/views/banks/edit.html.haml
.content-wrapper
  %section.content-header
    %h1
      Banks
    %section.content
      .row
        = render :partial => 'form'

app/views/banks/index.html.haml
.content-wrapper
  %section.content-header
    %h1
      Banks
  %section.content
    = render 'layouts/flash_notice'
    .row
      = link_to 'New Bank', new_bank_path, class: 'btn bg-red margin'
      .spacer5
      .col-xs-12
        .box
          .box-body
            %table#example2.table.table-bordered.table-hover.dataTable{"aria-describedby" => "example2_info"}
              - if @banks.present?
                %thead
                  %tr
                    %th Sr.No.
                    %th Name
                    %th Email
                    %th Contact
                    / %th Actions
                %tbody
                  = render :partial => 'list_of_banks'
              - else
                No Bank Found
      .col-xs-6
        .dataTables_paginate.paging_bootstrap
          %ul.pagination
            = paginate @banks

app/views/banks/new.html.haml
.content-wrapper
  %section.content-header
    %h1
      Banks
    %section.content
      .row
        = render :partial => 'form'

app/views/banks/show.html.haml
.content-wrapper
  %section.content-header
    %h1 Bank Detail
  .section.content
    .row
      .col-md-6
        .box.box-primary
          .box-body
            Bank Name:
            = @bank.bank_name
            .spacer5
            Email:
            = @bank.email
            .spacer5
            Contact:
            = @bank.phone_number
            .spacer5
            Address:
            = @bank.address.street
            .spacer5
            = @bank.address.city.titleize
            = @bank.address.state.code
            .spacer5
            = @bank.address.country.name
    - if can? :manage, Bank
      .row
        = link_to 'Edit', edit_bank_path(@bank), class: 'btn bg-red margin'

app/views/ci_companies/_form.html.haml
= form_for @ci_company do |f|
  .col-md-6
    .box.box-primary
      .box-header
        %h3.box-title
        .box-body
          - if @ci_company.errors[:ci_company_name].present?
            .form-group.has-error
              = f.label :Name
              = f.text_field :ci_company_name, placeholder: "#{@ci_company.errors.messages[:ci_company_name].join(",")}", :class => 'form-control'
          - else
            .form-group
              = f.label :Name
              = f.text_field :ci_company_name, placeholder: 'Enter Name', :class => 'form-control'
          .form-group
            = f.label :Phone_Number
            = f.text_field :phone_number, placeholder: 'Enter Phone', :class => 'form-control'
          - if @ci_company.errors[:ci_company_email].present?
            .form-group.has-error
              = f.label :Email
              = f.text_field :ci_company_email, placeholder: "#{@ci_company.errors.messages[:ci_company_email].join(",")}", :class => 'form-control'
          - else
            .form-group
              = f.label :Email
              = f.text_field :ci_company_email, placeholder: 'Enter email', :class => 'form-control'
          .form-group
            = f.label :URL
            = f.text_field :url, placeholder: 'Enter URL', :class => 'form-control'
  .col-md-6
    .box.box-warning
      .box-header
        %h3.box-title Address
        .box-body
          = f.fields_for :address do |addresses_form|
            .form-group
              #{addresses_form.label :Country}
            .form-group
              #{addresses_form.collection_select :country_id, Country.all, :id, :name, {include_blank: false}, {class: 'form-control'}}
            .form-group
              #{addresses_form.label :State}
            .form-group
              #{addresses_form.collection_select :state_id, State.all, :id, :name, {include_blank: 'Select State'}, {class: 'form-control'}}
            .form-group
              #{addresses_form.label :Street}
            .form-group
              #{addresses_form.text_field :street, :class => 'form-control', placeholder: 'Enter Street'}
            .form-group
              #{addresses_form.label :City}
            .form-group
              #{addresses_form.text_field :city, :class => 'form-control', placeholder: 'Enter City'}
    .box-warning{:style => 'position: relative;right: 513px;'}
      .box-footer
        %button.btn.btn-primary{:type => 'submit'} Submit

app/views/ci_companies/_list_of_ci_companies.html.haml
- @ci_companies.each_with_index do |ci_company, index|
  %tr
    %td<
      = index + 1
    %td<
      = ci_company.ci_company_name
    %td<
      = ci_company.ci_company_email
    %td<
      = ci_company.phone_number
    %td<
      / = link_to(edit_ci_company_path(ci_company), class: 'green', title: 'Edit') do
      /   %i.fa.fa-fw.fa-pencil
      / = link_to(ci_company_path(ci_company), method: :delete, data: { confirm: 'Are you sure?' }, class: 'green', title: 'Delete') do
      /   %i.fa.fa-fw.fa-bitbucket

app/views/ci_companies/edit.html.haml
.content-wrapper
  %section.content-header
    %h1
      Ci Companies
    %section.content
      .row
        = render :partial => 'form'

app/views/ci_companies/index.html.haml
.content-wrapper
  %section.content-header
    %h1
      CI Companies
  %section.content
    = render 'layouts/flash_notice'
    .row
      /  - if can? :manage, CiCompany= 
      = link_to 'New Ci Company', new_ci_company_path, class: 'btn bg-red margin'
      .spacer5
      .col-xs-12
        .box
          .box-body
            %table#example1.table.table-bordered.table-striped
              - if @ci_companies.present?
                %thead
                  %tr
                    %th Sr.No.
                    %th Name
                    %th Email
                    %th Contact
                    / %th Actions
                %tbody
                  = render partial: 'list_of_ci_companies'
              - else
                No CI Company Found
      .col-xs-6
        .dataTables_paginate.paging_bootstrap
          %ul.pagination
            = paginate @ci_companies

app/views/ci_companies/new.html.haml
.content-wrapper
  %section.content-header
    %h1
      Ci Companies
    %section.content
      .row
        = render :partial => 'form'

app/views/layouts/_flash_notice.html.haml
- flash.each do |name, msg|
  .box-body{:style => 'position: relative;left: -13px;'}
    .alert.alert-success.alert-dismissable
      %h4
        %i.icon.fa.fa-check
        = msg
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} ×

app/views/layouts/_header.html.erb
<header class="main-header">
  <a class="logo" href="#">
    <b>> Inspect</b>
    DATE
  </a>
  <!-- Header Navbar: style can be found in header.less
  -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button
    -->
    <a class="sidebar-toggle" data-toggle="offcanvas" href="#" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu
    -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        / <%# if current_user.present? %>
          <li class="dropdown user user-menu">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <span class="hidden-xs">Welcome</span>
            </a>
          </li>
          <li class="dropdown user user-menu">
            / <%#= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-toggle' %>
          </li>
        / <% else %>
          <li class="dropdown user user-menu">
            <!-- = link_to 'System Admin', new_user_session_path, class: 'dropdown-toggle'
            -->
          </li>
        / <%# end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_left_side_bar.html.erb
<aside clas9s="main-sidebar">
  <section class="sidebar">
    <ul class="sidebar-menu">
      / <%# if current_user.is_system_admin? || current_user.is_bank_admin? %>
        <li>
          <%= link_to set_add_show_bank_link do %>
            <i class="fa fa-hospital-o"></i>
            <span>
              <%#= set_bank_label %>
            </span>
          <% end %>
        </li>
      / <%# end %>
      / <%# if current_user.is_system_admin? || current_user.is_bank_admin? || current_user.is_banking_professional? %>
        <li>
          <%= link_to banking_users_path do %>
            <i class="fa fa-users"></i>
            <span>Banking Professionals</span>
          <% end %>
        </li>
      / <%# end %>
      / <%# if current_user.is_system_admin? || current_user.is_cic_admin? %>
        <li>
          <%= link_to ci_companies_path do %>
            <i class="fa fa-building-o"></i>
            <span>CI Company</span>
          <% end %>
        </li>
      / <%# end %>
      / <%# if current_user.is_system_admin? || current_user.is_cic_admin? || current_user.construction_inspector? %>
        <li>
          <%= link_to company_inspectors_path  do %>
            <i class="fa fa-user"></i>
            <span>Company Inspector</span>
          <% end %>
        </li>
      / <%# end %>
    </ul>
  </section>
</aside>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "UTF-8"}/
    %title InspectDate
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body.skin-red
    .wrapper
      = render partial: 'layouts/header'
      = render partial: 'layouts/left_side_bar' #if current_user.present?
      = yield 

app/views/layouts/auth.html.haml
!!!
%html
  %head
    %meta{:charset => "UTF-8"}/
    %title InspectDate
    %meta{:content => "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield